version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:80
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - app-network

#   notification-service:
#     build:
#       context: ./NotificationService
#       dockerfile: Dockerfile
#     depends_on:
#       - rabbitmq
#     healthcheck:
#       test: ["CMD-SHELL", "grep 'healthy' /proc/1/fd/1 || exit 1"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#     networks:
#       - app-network

networks:
  app-network:
    driver: bridge